version: '3.7'
services: 
    postgres_db:
        image: postgres:latest
        restart: always
        container_name: database_container
        network_mode: bridge
        ports: 
            - "5432:5432"
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes: 
            - .\migration\populate_db.sql:/docker-entrypoint-initdb.d/populate_db.sql  
    api_server:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres_db
        networks:
            - default
        ports:
            - "8080:8080" 